service:
  name: alter-knit-api

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 3003
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    stages:
    - dev

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    #3
    ALTERKNIT_TABLE: AlterKnit-${self:provider.stage}
    SENDGRID_API_KEY: asldfkls

functions:

  hello:
    handler: src/functions/hello/handler.check
    events:
      - http:
          method: post
          path: hello
          cors:
            origins:
              - '*'
            headers:
              - Accept
              - Origin
              - DNT
              - User-Agent
              - Referer
              - Content-Type
              - X-Amz-Date
              - x-amz-date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  createOrder:
    handler: src/functions/createOrder/handler.handler
    timeout: 30
    memorySize: 1024
    events:
      - http:
          method: post
          path: order
          cors:
            origins:
              - '*'
            headers:
              - Accept
              - Origin
              - DNT
              - User-Agent
              - Referer
              - Content-Type
              - X-Amz-Date
              - x-amz-date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ALTERKNIT_TABLE}

  getAllOrder:
    handler: src/functions/getAllOrder/handler.handler
    events:
      - http:
          method: get
          path: order
          cors:
            origins:
              - '*'
            headers:
              - Accept
              - Origin
              - DNT
              - User-Agent
              - Referer
              - Content-Type
              - X-Amz-Date
              - x-amz-date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ALTERKNIT_TABLE}
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: arn:aws:secretsmanager:us-east-1:722399669416:secret:staging/alterknit-TkXahJ

  contactUs:
    handler: src/functions/contactUs/handler.handler
    timeout: 10
    events:
      - http:
          method: post
          path: contact-us
          cors:
            origins:
              - '*'
            headers:
              - Accept
              - Origin
              - DNT
              - User-Agent
              - Referer
              - Content-Type
              - X-Amz-Date
              - x-amz-date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
    iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: arn:aws:secretsmanager:us-east-1:722399669416:secret:staging/alterknit-TkXahJ

resources:
  Resources:
    TodosDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ALTERKNIT_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        # AWS Free tier
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        # For production I'll recommend you to use this one instead, so you pay only for what you use
        # BillingMode: PAY_PER_REQUEST